styleguide: plataformatec/linters
engines:
  credo:
    enabled: true
  fixme:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: false
  scss-lint:
    enabled: true
  remark-lint:
    enabled: true
exclude_paths:
  - config
  - priv/repo
  - test
  - web/static/vendor
  - web/static/css/vendor
