language: elixir
elixir: 1.3.2
otp_release: 19.0
sudo: false
addons:
  postgresql: "9.4"
script:
  - MIX_ENV=test mix ecto.create
  - mix test --include integration
  - MIX_ENV=test mix run priv/repo/seeds.exs
  - git clone https://github.com/hexpm/hex ../hex && cd ../hex && mix deps.get && mix test --include integration
notifications:
  recipients:
    - eric.meadows.jonsson@gmail.com
