language: elixir
otp_release:
  - 17.5
elixir:
  - 1.0.5
  - 1.1.1
sudo: false
addons:
  postgresql: "9.4"
before_script:
  - mix archive.install http://s3.hex.pm/installs/hex.ez --force
  - mix deps.get
  - MIX_ENV=test mix deps.compile
script:
  - MIX_ENV=test mix compile
  - mix test --include integration
notifications:
  recipients:
    - eric.meadows.jonsson@gmail.com
matrix:
  include:
    - otp_release: 18.1
      elixir: master
